name: Zephyr Deployment
description: Performs a build of the affected projects

# Inside of Zephyr we will need to configure things so that build uploads 
# from the main branch always goes into a specific environment
inputs:
  auth_token:  # Define the input
    description: 'Zephyr authentication token'
    required: true

runs:
  using: "composite"
  steps:
    # Derive appropriate SHAs for base and head for `nx affected` commands
    - uses: nrwl/nx-set-shas@v4

    - name: Run Build
      id: affected-build
      continue-on-error: false
      env:
          ZE_SECRET_TOKEN: ${{ inputs.auth_token }}
          WITH_ZE: "1"
      run: |
        if [ -z "$ZE_SECRET_TOKEN" ]; then
          echo "Error: ZE_SECRET_TOKEN is not set"
          exit 1
        fi
        pnpm nx affected -t bundle:ios
      shell: bash