name: Zephyr Repack Plugin E2E testing
#on:
#  repository_dispatch:
#    types: [trigger-from-zephyr-packages]

on:
  pull_request:
    branches:
      - main

jobs:
  zephyr-deployment-ios:
    uses: ./.github/workflows/zephyr-deployment.yml
    with:
      platform: ios
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}

  ios-tests:
    needs: zephyr-deployment-ios
    uses: ./.github/workflows/e2e-ios.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
    with:
      build-zephyr-repack-plugin-locally: true

  zephyr-deployment-android:
    if: always()
    needs: ios-tests
    uses: ./.github/workflows/zephyr-deployment.yml
    with:
      platform: android
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}

  android-tests:
    if: always()
    needs: zephyr-deployment-android
    uses: ./.github/workflows/e2e-android.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
    with:
      build-zephyr-repack-plugin-locally: true

