name: Zephyr Repack Plugin E2E testing

on:
  workflow_dispatch:

jobs:
  zephyr-deployment-ios:
    uses: ./.github/workflows/zephyr-deployment.yml
    with:
      platform: ios
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}

  ios-tests:
    needs: zephyr-deployment-ios
    uses: ./.github/workflows/e2e-ios.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
    with:
      build-zephyr-repack-plugin-locally: true

  zephyr-deployment-android:
    if: always()
    needs: ios-tests
    uses: ./.github/workflows/zephyr-deployment.yml
    with:
      platform: android
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}

  android-tests:
    if: always()
    needs: zephyr-deployment-android
    uses: ./.github/workflows/e2e-android.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
    with:
      build-zephyr-repack-plugin-locally: true

  report-status:
    if: always()
    needs: [zephyr-deployment-ios, ios-tests, zephyr-deployment-android, android-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Generate Job Statuses and Log Links
        id: collect-status
        run: |
          echo "ZE_DEPLOYMENT_IOS=${{ needs.zephyr-deployment-ios.result }}" >> $GITHUB_ENV
          echo "IOS_TESTS=${{ needs.ios-tests.result }}" >> $GITHUB_ENV
          echo "ZE_DEPLOYMENT_ANDROID=${{ needs.zephyr-deployment-android.result }}" >> $GITHUB_ENV
          echo "ANDROID_TESTS=${{ needs.android-tests.result }}" >> $GITHUB_ENV

          if [[ "${{ needs.zephyr-deployment-ios.result }}" == "success" && \
                "${{ needs.ios-tests.result }}" == "success" && \
                "${{ needs.zephyr-deployment-android.result }}" == "success" && \
                "${{ needs.android-tests.result }}" == "success" ]]; then
            echo "WORKFLOW_STATUS=success" >> $GITHUB_ENV
          else
            echo "WORKFLOW_STATUS=failure" >> $GITHUB_ENV
          fi

      - name: Generate Job Log Links
        id: collect-logs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get job details from GitHub API
          JOBS_JSON=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs --jq '.jobs')

          # Extract job IDs based on job names
          IOS_ZEPHYR_DEPLOYMENT_JOB_ID=$(echo "$JOBS_JSON" | jq -r '.[] | select(.name == "zephyr-deployment-ios") | .id')
          ANDROID_ZEPHYR_DEPLOYMENT_JOB_ID=$(echo "$JOBS_JSON" | jq -r '.[] | select(.name == "zephyr-deployment-android") | .id')
          IOS_TESTS_JOB_ID=$(echo "$JOBS_JSON" | jq -r '.[] | select(.name == "ios-tests") | .id')
          ANDROID_TESTS_JOB_ID=$(echo "$JOBS_JSON" | jq -r '.[] | select(.name == "android-tests") | .id')

          # Construct job log URLs
          echo "IOS_DEPLOYMENT_LOGS=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${IOS_ZEPHYR_DEPLOYMENT_JOB_ID}" >> $GITHUB_ENV
          echo "IOS_TESTS_LOGS=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${IOS_TESTS_JOB_ID}" >> $GITHUB_ENV
          echo "ANDROID_DEPLOYMENT_LOGS=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${ANDROID_ZEPHYR_DEPLOYMENT_JOB_ID}" >> $GITHUB_ENV
          echo "ANDROID_TESTS_LOGS=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${ANDROID_TESTS_JOB_ID}" >> $GITHUB_ENV

      - name: Report Results to `zephyr-packages`
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'MikitasK',
              repo: 'zephyr-packages',
              workflow_id: 'zephyr_repack_plugin_e2e_results.yml',
              ref: 'ci/zephyr-repack-plugin-e2e-trigger',
              inputs: {
                workflow_status: "${{ env.WORKFLOW_STATUS }}",
                run_url: "https://github.com/ZephyrCloudIO/zephyr-repack-example/actions/runs/${{ github.run_id }}",
                zephyr_deployment_ios_status: "${{ env.ZE_DEPLOYMENT_IOS }}",
                ios_tests_status: "${{ env.IOS_TESTS }}",
                zephyr_deployment_android_status: "${{ env.ZE_DEPLOYMENT_ANDROID }}",
                android_tests_status: "${{ env.ANDROID_TESTS }}",
                ios_deployment_logs_url: "${{ env.IOS_DEPLOYMENT_LOGS }}",
                ios_tests_logs_url: "${{ env.IOS_TESTS_LOGS }}",
                android_deployment_logs_url: "${{ env.ANDROID_DEPLOYMENT_LOGS }}",
                android_tests_logs_url: "${{ env.ANDROID_TESTS_LOGS }}"
              }
            });


