name: Zephyr Repack Plugin E2E testing
#on:
#  repository_dispatch:
#    types: [trigger-from-zephyr-packages]

on:
  pull_request:
    branches:
      - main

jobs:
  zephyr-deployment:
    uses: ./.github/workflows/zephyr-deployment.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}

  ios-tests:
    needs: zephyr-deployment
    uses: ./.github/workflows/e2e-ios.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
    with:
      build-zephyr-repack-plugin-locally: true

  android-tests:
    needs: zephyr-deployment
    uses: ./.github/workflows/e2e-android.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
    with:
      build-zephyr-repack-plugin-locally: true
