name: E2E Android Tests

on:
  pull_request:
    branches:
      - main

jobs:
  android-e2e-tests:
    runs-on: ubuntu-latest
    env:
      MAESTRO_VERSION: 1.39.4
      ANDROID_EMULATOR_API_LEVEL: 28
      ANDROID_EMULATOR_TARGET: default
      ANDROID_EMULATOR_ARCH: x86
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup KVM (Required for Android Emulator)
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH

      - name: Setup JS Environment and Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Create AVD and generate snapshot for caching
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_EMULATOR_API_LEVEL }}
          target: ${{ env.ANDROID_EMULATOR_TARGET }}
          arch: ${{ env.ANDROID_EMULATOR_ARCH }}
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot for caching."

      - name: Run Android E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_EMULATOR_API_LEVEL }}
          target: ${{ env.ANDROID_EMULATOR_TARGET }}
          arch: ${{ env.ANDROID_EMULATOR_ARCH }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            chmod +x ./.github/scripts/run-android-maestro-tests.sh
            ./.github/scripts/run-android-maestro-tests.sh
      - name: Upload Maestro Logs on Failure
        if: failure() # Runs only if any of the previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: maestro-logs-android
          path: ~/.maestro/tests/
