name: Build remote iOS

on:
  pull_request:
    branches:
      - main

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  pull-requests: write
  contents: read

jobs:
  build-remote-ios:
    runs-on: macos-latest
    timeout-minutes: 60 # Set a timeout for the job to prevent it from running indefinitely
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup-dependencies
      - uses: callstackincubator/ios@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          destination: 'simulator' # or 'device'
          scheme: 'host'
          configuration: 'Debug'
          working-directory: './apps/mobile-host'
