name: Mobile E2E Tests Trigger

on:
  workflow_call:
    secrets:
      ZE_SECRET_TOKEN:
        required: true
        description: "Zephyr secret token"

jobs:
  zephyr-deployment:
    uses: ./.github/workflows/zephyr-deployment.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}

  ios-tests:
    needs: zephyr-deployment
    uses: ./.github/workflows/e2e-ios.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}

  android-tests:
    needs: zephyr-deployment
    uses: ./.github/workflows/e2e-android.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
