name: Zephyr Repack Plugin E2E testing
#on:
#  repository_dispatch:
#    types: [trigger-from-zephyr-packages]

on:
  pull_request:
    branches:
      - main

jobs:
  build-zephyr-repack-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run a Task
        run: echo "Workflow triggered by the submodule"

      - name: Add "zephyr-packages" repo as submodule
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_URL="https://${GITHUB_TOKEN}@github.com/ZephyrCloudIO/zephyr-packages.git"
          # TODO: Change branch param from "repack-fixed" to "main" after merging this PR: https://github.com/ZephyrCloudIO/zephyr-packages/pull/4
          git submodule add -b main $REPO_URL submodules/zephyr-packages
          git submodule update --init --recursive

      - name: Build Zephyr Repack Plugin locally
        uses: ./.github/actions/build-zephyr-repack-plugin

      - name: Update Zephyr Repack Plugin version
        run: |
          chmod +x ./.github/scripts/update-zephyr-repack-plugin-version.sh
          ./.github/scripts/update-zephyr-repack-plugin-version.sh
  e2e-tests:
    needs: build-zephyr-repack-plugin
    uses: ./.github/workflows/mobile-e2e-trigger.yml
    secrets:
      ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
