name: Zephyr Deployment

on:
  workflow_call:
    inputs:
      ZE_SECRET_TOKEN:
        description: 'Zephyr token'
        required: true
        type: string

jobs:
    zephyr-deployment:
        runs-on: ubuntu-latest
        timeout-minutes: 10 # Set a timeout for the job to prevent it from running indefinitely
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: ./.github/actions/setup-dependencies
            - name: Deploy to Zephyr
              shell: bash
              env:
                  ZE_SECRET_TOKEN: ${{ inputs.ZE_SECRET_TOKEN }}
                  WITH_ZE: "1"
                  ZC: "1"
              run: |
                if [ -z "$ZE_SECRET_TOKEN" ]; then
                  echo "Error: ZE_SECRET_TOKEN is not set"
                  exit 1
                fi
                pnpm nx run-many -t bundle:ios